export const SQUARE_CARD_ALPHA_HEIGHT = 1254
export const SQUARE_CARD_ALPHA_BOTTOM_ROW = 1134
export const SQUARE_CARD_ALPHA_BOTTOM =
  SQUARE_CARD_ALPHA_BOTTOM_ROW / SQUARE_CARD_ALPHA_HEIGHT

export const VIDEO_CLIP_INFO_CORNER_RADIUS = 15

export const DETAIL_PANEL_ALPHA_WIDTH = 1080
export const DETAIL_PANEL_ALPHA_HEIGHT = 1728
export const DETAIL_PANEL_ALPHA_LEFT = 103 / DETAIL_PANEL_ALPHA_WIDTH
export const DETAIL_PANEL_ALPHA_RIGHT = 984 / DETAIL_PANEL_ALPHA_WIDTH
export const DETAIL_PANEL_ALPHA_TOP = 40 / DETAIL_PANEL_ALPHA_HEIGHT
export const DETAIL_PANEL_ALPHA_BOTTOM = 1688 / DETAIL_PANEL_ALPHA_HEIGHT
export const DETAIL_PANEL_CORNER_RADIUS_RATIO = 53 / DETAIL_PANEL_ALPHA_WIDTH
